from utilities import checkValidWebsite
from error_handler import *
from bs4 import BeautifulSoup as bs

def searchByName(sb, website : str, name : str) -> list[tuple[str,str]]:
    """Searches for a manga by its name on the website.
    Args :
        website : website to search on
        name : name of the manga
        
    Returns :
        list of tuples (manga name, manga url)"""
    if not checkValidWebsite(website):
        raise InvalidWebsite(f"{website} not supported.")
    sb.driver.get(f"https://{website}/?s={'+'.join(name.split(' '))}") #replace every blank space by a + 
    soup = bs(sb.driver.page_source,'html.parser')
    children_divs = [a.findChildren()[0] for a in soup.find_all("div",{"class" : "bsx"})]
    results_list = [(a["title"],a["href"]) for a in children_divs]
    return results_list

def chooseFromResults(results_list : list[tuple[str,str]]) -> str:
    """Asks the user to choose a manga from the results list.
    Args :
        results_list : list of tuples (manga name, manga url), generated by searchByName
    Returns :
        url of the chosen manga
    """
    res = int(input(f"From your input, here are the available results.Select one : {', '.join([i[0] for i in results_list])}\n"))
    return results_list[res - 1][1]